// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRjB8tHBQ1pY7epZyyXFa0sWpnKP96YT4',
    appId: '1:721939187811:web:41054bc9eaed0eb1841056',
    messagingSenderId: '721939187811',
    projectId: 'selfcooking-ac3b0',
    authDomain: 'selfcooking-ac3b0.firebaseapp.com',
    storageBucket: 'selfcooking-ac3b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD06F5ghBdvh7bfoa7gyP5WbYP5WCY2zxs',
    appId: '1:721939187811:android:771aba67aea93ac1841056',
    messagingSenderId: '721939187811',
    projectId: 'selfcooking-ac3b0',
    storageBucket: 'selfcooking-ac3b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoY0dZmyQUVdcb2QfYmbEk_0xCwNJIHtY',
    appId: '1:721939187811:ios:fbf0ffa10a2f5507841056',
    messagingSenderId: '721939187811',
    projectId: 'selfcooking-ac3b0',
    storageBucket: 'selfcooking-ac3b0.firebasestorage.app',
    iosBundleId: 'com.example.rice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoY0dZmyQUVdcb2QfYmbEk_0xCwNJIHtY',
    appId: '1:721939187811:ios:fbf0ffa10a2f5507841056',
    messagingSenderId: '721939187811',
    projectId: 'selfcooking-ac3b0',
    storageBucket: 'selfcooking-ac3b0.firebasestorage.app',
    iosBundleId: 'com.example.rice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRjB8tHBQ1pY7epZyyXFa0sWpnKP96YT4',
    appId: '1:721939187811:web:e339c3b791623212841056',
    messagingSenderId: '721939187811',
    projectId: 'selfcooking-ac3b0',
    authDomain: 'selfcooking-ac3b0.firebaseapp.com',
    storageBucket: 'selfcooking-ac3b0.firebasestorage.app',
  );
}
